{% set name = "pygeoogc" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 417b7c0fbc7a6fd0f6175d0050882626a28453d563162eced363e8170ffd0666

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - setuptools
    - dataclasses
    - defusedxml
    - owslib
    - pyproj
    - requests
    - shapely
    - orjson

test:
  imports:
    - pygeoogc

about:
  home: https://github.com/cheginit/pygeoogc
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An interface to ArcGIS RESTful-, WFS-, and WMS-based web services

  description: |
    PyGeoOGC is a part Hydrodata software stack that provides interfaces to
    ArcGIS RESTful-, WFS-, and WMS-based web services.
  doc_url: https://hydrodata.readthedocs.io
  dev_url: https://github.com/cheginit/pygeoogc

extra:
  recipe-maintainers:
    - cheginit
