{% set name = "pygeoogc" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygeoogc-{{ version }}.tar.gz
  sha256: d077972e9664f347a116694b58368accf21d994072f23b4d418a949d9fa2ee1f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - async-retriever <0.19,>=0.18
    - cytoolz
    - defusedxml
    - joblib
    - multidict
    - owslib >=0.27.2
    - pyproj >=3.0.1
    - requests
    - requests-cache >=0.9.6
    - shapely >=2
    - ujson
    - url-normalize >=1.4
    - urllib3
    - yarl

test:
  imports:
    - pygeoogc
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hyriver/pygeoogc
  summary: An interface to ArcGIS RESTful-, WFS-, and WMS-based services.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
