{% set name = "pygeoogc" %}
{% set version = "0.15.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygeoogc-{{ version }}.tar.gz
  sha256: 4c6dedc464cc28376feb07940700ab7a50f797360699aa5e2d3ba0b33602b00f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - setuptools-scm >=7
    - pip
  run:
    - python >=3.8
    - async-retriever <0.16,>=0.15.2
    - cytoolz
    - defusedxml
    - joblib
    - multidict
    - owslib >=0.27.2
    - pyproj >=3.0.1
    - requests
    - requests-cache >=0.9.6
    - shapely >=1.8.5
    - ujson
    - url-normalize >=1.4
    - urllib3
    - yarl

test:
  imports:
    - pygeoogc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hyriver/pygeoogc
  summary: An interface to ArcGIS RESTful-, WFS-, and WMS-based services.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
