{% set name = "pygeoogc" %}
{% set version = "0.13.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygeoogc-{{ version }}.tar.gz
  sha256: 2657d26d5dbbde07eeb7df43cd6f54b28fdebf5725261bc0086dc0def1747924

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - async_retriever >=0.3.2
    - cytoolz
    - defusedxml
    - owslib
    - pydantic
    - pyproj >=2.2
    - python >=3.7
    - pyyaml
    - requests
    - requests-cache >=0.9.1
    - shapely >=1.7
    - urllib3
    - importlib_metadata

test:
  imports:
    - pygeoogc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cheginit/pygeoogc
  summary: An interface to ArcGIS RESTful-, WFS-, and WMS-based services.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
