{% set name = "pygeoogc" %}
{% set version = "0.13.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygeoogc-{{ version }}.tar.gz
  sha256: 13b5afae74ff0040193742eaef9c9c5b28e85ab928f19ea5fbb096e8ccbc1042

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools-scm
  run:
    - python >=3.8
    - pyyaml
    - defusedxml
    - owslib >=0.27.2
    - urllib3
    - pyproj >=2.2
    - requests-cache >=0.9.6
    - requests
    - cytoolz
    - shapely >=1.8
    - pydantic
    - async_retriever >=0.3.5

test:
  imports:
    - pygeoogc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hyriver/pygeoogc
  summary: An interface to ArcGIS RESTful-, WFS-, and WMS-based services.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
