{% set name = "pygeoogc" %}
{% set version = "0.12.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygeoogc-{{ version }}.tar.gz
  sha256: 0159a177bcd3b05642744c4e8159c49428c317ba4113b710cfa48dee6bdfc7bc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - async_retriever >=0.3.1
    - cytoolz
    - defusedxml
    - owslib
    - pydantic
    - pyproj >=2.2
    - python >=3.7
    - pyyaml
    - requests
    - requests-cache >=0.8
    - shapely >=1.6
    - urllib3
    - importlib_metadata

test:
  imports:
    - pygeoogc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cheginit/pygeoogc
  summary: An interface to ArcGIS RESTful-, WFS-, and WMS-based services.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
