{% set name = "pygeoogc" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygeoogc-{{ version }}.tar.gz
  sha256: ea89cbed81c043c3f291b09aeb1847d7cfe48a71bfe879c883ec8ede1ec95a7e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - cytoolz
    - defusedxml
    - owslib
    - pydantic
    - pyproj
    - python >=3.7
    - pyyaml
    - requests
    - requests-cache
    - shapely
    - simplejson
    - urllib3

test:
  imports:
    - pygeoogc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cheginit/pygeoogc
  summary: An interface to ArcGIS RESTful-, WFS-, and WMS-based services.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
