{% set name = "pygeoogc" %}
{% set version = "0.13.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygeoogc-{{ version }}.tar.gz
  sha256: baf36d05bae5b890b1434011a9e267635552dbcd4cd8105b685951d38a12af07

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - async_retriever >=0.3.2
    - cytoolz
    - defusedxml
    - owslib <0.26
    - pydantic
    - pyproj >=2.2
    - python >=3.8
    - pyyaml
    - requests
    - requests-cache >=0.9.1
    - shapely >=1.7
    - urllib3

test:
  imports:
    - pygeoogc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cheginit/pygeoogc
  summary: An interface to ArcGIS RESTful-, WFS-, and WMS-based services.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
