{% set name = "pygeoogc" %}
{% set version = "0.13.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygeoogc-{{ version }}.tar.gz
  sha256: 5f9e25b53ad610ecc30c4cc4a44affb35660ed3e08a3359c551d9b9b83422c8c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools-scm
  run:
    - python >=3.8
    - async-retriever >=0.3.5
    - cytoolz
    - defusedxml
    - loguru
    - owslib >=0.27.2
    - pyproj >=2.2
    - pyyaml
    - requests
    - requests-cache >=0.9.6
    - shapely >=1.8
    - urllib3

test:
  imports:
    - pygeoogc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hyriver/pygeoogc
  summary: An interface to ArcGIS RESTful-, WFS-, and WMS-based services.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
