{% set name = "pygeoogc" %}
{% set version = "0.13.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygeoogc-{{ version }}.tar.gz
  sha256: 16d05fb122122a830f5f991f9ae02e33c81f030c128591da3cb1bff4cc5fbef0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools-scm
  run:
    - python >=3.8
    - async-retriever >=0.3.10
    - cytoolz
    - defusedxml
    - joblib
    - loguru
    - multidict
    - owslib >=0.27.2
    - pyproj >=2.2
    - pyyaml
    - requests
    - requests-cache >=0.9.6
    - shapely >=1.8
    - url-normalize >=1.4
    - urllib3
    - yarl

test:
  imports:
    - pygeoogc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hyriver/pygeoogc
  summary: An interface to ArcGIS RESTful-, WFS-, and WMS-based services.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
