{% set name = "pygeoogc" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygeoogc-{{ version }}.tar.gz
  sha256: a817e02102868f8a2bb17d0324953b6d0f577a949cbad89e154e20c5e7fed3c6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - setuptools-scm >=7
    - pip
  run:
    - python >=3.8
    - async-retriever >=0.14
    - cytoolz
    - defusedxml
    - joblib
    - multidict
    - owslib >=0.27.2
    - pyproj >=2.2
    - requests
    - requests-cache >=0.9.6
    - shapely >=1.8
    - ujson
    - url-normalize >=1.4
    - urllib3
    - yarl

test:
  imports:
    - pygeoogc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hyriver/pygeoogc
  summary: An interface to ArcGIS RESTful-, WFS-, and WMS-based services.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
