{% set name = "pygeoogc" %}
{% set version = "0.11.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygeoogc-{{ version }}.tar.gz
  sha256: aa90fdda38b3fcbde117c6ba8c27b01f4807263dfaec1d0a09ea332d577c9bb3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - async_retriever >=0.2
    - cytoolz
    - defusedxml
    - owslib
    - pydantic
    - pyproj >=2.2
    - python >=3.7
    - pyyaml
    - requests
    - requests-cache
    - shapely >=1.6
    - simplejson
    - urllib3

test:
  imports:
    - pygeoogc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cheginit/pygeoogc
  summary: An interface to ArcGIS RESTful-, WFS-, and WMS-based services.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
